# Generated by Django 2.1.2 on 2019-04-08 11:34

import apps.users.managers
from django.db import migrations, models
import openawards.models


class Migration(migrations.Migration):

    dependencies = [
        ('openawards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users.managers.CCUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='authorship',
            field=models.CharField(choices=[('Y', 'Yes, I am the author, have permission, or the license authorizes this.'), ('N', "No, I don't own these rights, but I still want to upload this work, knowing that it might betransferred to another person or removed from the awards if there's a claim."), ('M', "I don't if I'm allowed or not to enroll this work to the awards, but I still want to upload this work, knowing that it might be transferred to another person or removed from the awards if there's a claim.")], default='Y', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=openawards.models.upload_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=1),
        ),
    ]
