# Generated by Django 2.1.2 on 2019-04-08 16:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('openawards', '0003_auto_20190408_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
