# Generated by Django 2.1.2 on 2019-04-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openawards', '0004_auto_20190408_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditacquisition',
            name='source',
            field=models.CharField(choices=[('C', 'Creation'), ('A', 'Admin'), ('P', 'PayPal'), ('D', 'Dev'), ('O', 'Coupon')], default='C', max_length=1),
        ),
    ]
