# Generated by Django 2.1.2 on 2019-05-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openawards', '0006_auto_20190409_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
