# Generated by Django 2.1.2 on 2019-09-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openawards', '0007_auto_20190503_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditacquisition',
            name='source',
            field=models.CharField(choices=[('C', 'Creation'), ('A', 'Admin'), ('P', 'PayPal'), ('D', 'Dev'), ('O', 'Coupon'), ('R', 'Vote received')], default='C', max_length=1),
        ),
    ]
