# Generated by Django 2.1.2 on 2019-10-01 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openawards', '0008_auto_20190926_1945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-voted_on']},
        ),
    ]
