version: "3.3"

services:
  app:
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile
    command: gunicorn OpenAwards.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ../:/srv/app/
    environment:
      - DB_HOST=db
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - /srv/data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5432:5432
#  nginx:
#    build:
#      context: ../
#      dockerfile: ./docker/nginx/Dockerfile
#    volumes:
#      - ../staticfiles:/srv/app/staticfiles
#    ports:
#      - ${NGINX_PORT}:80
#    depends_on:
#      - app
